### ISSUE TITLE
[Fearture Request] Block requests from the local net.

### ISSUE THREAD

**Issue by archef2000** [droscy/esphome#13]
First thanks for the work

Feature request for an option for when the network is not in your contol so no one can access the esp outside the vpn.
So an option to only expose the web server, api, ota update, etc to the wireguard tunnel would be very appreciated.

**Comment by droscy** [comment]
Hi @archef2000, it is a great idea but I don't think it is feasible from wireguard side because I know only two ways for achieving it and neither of them involve wireguard directly:

1. any server application should not listen to any interface but only to the wireguard one, this requires any component to "rebind" to a wg interface after wg setup
2. use a firewall inside the esp device

I will explore the second solution, maybe some sort of firewall exists.

The Wireguard component has been merged to the official `dev` branch so any issure/request should be now opened in official repos. Could you please reopen this here https://github.com/esphome/feature-requests/ maybe someone with more network knowledge then me have other solutions.

**Comment by archef2000** [comment]
Moved it thanks
